"""Centralized checksum registry API for WebAssembly toolchain

This module provides a unified API for accessing tool checksums from JSON files.
"""

def _load_tool_checksums_from_json(repository_ctx, tool_name):
    """Load checksums for a tool from JSON file

    This is the ONLY source of truth for tool checksums.
    JSON files are generated by the checksum_updater tool.

    Args:
        repository_ctx: Repository context for file operations
        tool_name: Name of the tool (e.g., 'wasm-tools', 'wit-bindgen')

    Returns:
        Dict: Tool data from JSON file

    Raises:
        fail: If JSON file not found
    """
    json_file = repository_ctx.path(Label("@rules_wasm_component//checksums/tools:{}.json".format(tool_name)))
    if not json_file.exists:
        fail("Checksums not found: //checksums/tools/{}.json\n".format(tool_name) +
             "Run 'bazel run //tools/checksum_updater -- --tool={}' to generate.".format(tool_name))

    content = repository_ctx.read(json_file)
    return json.decode(content)

def get_tool_checksum(repository_ctx, tool_name, version, platform):
    """Get verified checksum from centralized registry

    Args:
        repository_ctx: Repository context for file operations
        tool_name: Name of the tool (e.g., 'wasm-tools', 'wit-bindgen')
        version: Version string (e.g., '1.235.0')
        platform: Platform string (e.g., 'darwin_amd64', 'linux_amd64')

    Returns:
        String: SHA256 checksum, or None if not found
    """
    tool_data = _load_tool_checksums_from_json(repository_ctx, tool_name)

    versions = tool_data.get("versions", {})
    version_data = versions.get(version, {})
    platforms = version_data.get("platforms", {})
    platform_data = platforms.get(platform, {})

    return platform_data.get("sha256")

def get_tool_info(repository_ctx, tool_name, version, platform):
    """Get complete tool information from centralized registry

    Args:
        repository_ctx: Repository context for file operations
        tool_name: Name of the tool
        version: Version string
        platform: Platform string

    Returns:
        Dict: Complete platform information, or None if not found
    """
    tool_data = _load_tool_checksums_from_json(repository_ctx, tool_name)

    versions = tool_data.get("versions", {})
    version_data = versions.get(version, {})
    platforms = version_data.get("platforms", {})

    return platforms.get(platform)

def get_latest_version(repository_ctx, tool_name):
    """Get latest available version for a tool

    Args:
        repository_ctx: Repository context for file operations
        tool_name: Name of the tool

    Returns:
        String: Latest version, or None if tool not found
    """
    tool_data = _load_tool_checksums_from_json(repository_ctx, tool_name)

    return tool_data.get("latest_version")

def list_supported_platforms(repository_ctx, tool_name, version):
    """List all supported platforms for a tool version

    Args:
        repository_ctx: Repository context for file operations
        tool_name: Name of the tool
        version: Version string

    Returns:
        List: List of supported platform strings
    """
    tool_data = _load_tool_checksums_from_json(repository_ctx, tool_name)

    versions = tool_data.get("versions", {})
    version_data = versions.get(version, {})
    platforms = version_data.get("platforms", {})

    return list(platforms.keys())

def get_github_repo(repository_ctx, tool_name):
    """Get GitHub repository for a tool

    Args:
        repository_ctx: Repository context for file operations
        tool_name: Name of the tool

    Returns:
        String: GitHub repository in 'owner/repo' format, or None if not found
    """
    tool_data = _load_tool_checksums_from_json(repository_ctx, tool_name)

    return tool_data.get("github_repo")

def validate_tool_exists(repository_ctx, tool_name, version, platform):
    """Validate that a tool version and platform combination exists

    Args:
        repository_ctx: Repository context for file operations
        tool_name: Name of the tool
        version: Version string
        platform: Platform string

    Returns:
        Bool: True if the combination exists and has a checksum
    """
    checksum = get_tool_checksum(repository_ctx, tool_name, version, platform)
    return checksum != None and len(checksum) == 64  # Valid SHA256 length

def get_tool_metadata(repository_ctx, tool_name):
    """Get tool metadata including GitHub repo and latest version

    Args:
        repository_ctx: Repository context for file operations
        tool_name: Name of the tool

    Returns:
        Dict: Tool metadata including github_repo, latest_version, etc.
    """
    tool_data = _load_tool_checksums_from_json(repository_ctx, tool_name)

    return {
        "tool_name": tool_data.get("tool_name"),
        "github_repo": tool_data.get("github_repo"),
        "latest_version": tool_data.get("latest_version"),
        "build_type": tool_data.get("build_type", "binary"),
    }

def list_available_tools():
    """List all available tools in the registry

    Returns:
        List: List of available tool names
    """

    # Return tools that have fallback data available
    # Note: wizer removed - now part of wasmtime v39.0.0+, use `wasmtime wizer` subcommand
    return [
        "wasm-tools",
        "wit-bindgen",
        "wac",
        "wkg",
        "wasmtime",
        "wasi-sdk",
        "wasmsign2",
        "nodejs",
        "jco",
        "file-ops-component",
        "wasmsign2-cli",
        "go",
        "binaryen",
        "tinygo",
        "loom",
        "wsc",
    ]

def validate_tool_compatibility(tools_config):
    """Validate that tool versions are compatible with each other

    Args:
        tools_config: Dict mapping tool names to versions

    Returns:
        List: List of warning messages for compatibility issues
    """

    warnings = []

    # Define compatibility matrix (sourced from tool_versions.bzl)
    compatibility_matrix = {
        "1.243.0": {
            "wac": ["0.8.0", "0.8.1"],
            "wit-bindgen": ["0.46.0", "0.48.1", "0.49.0"],
            "wkg": ["0.11.0", "0.12.0", "0.13.0"],
            "wasmsign2": ["0.2.6"],
        },
        "1.235.0": {
            "wac": ["0.7.0", "0.8.0", "0.8.1"],
            "wit-bindgen": ["0.43.0", "0.46.0", "0.48.1", "0.49.0"],
            "wkg": ["0.11.0", "0.12.0", "0.13.0"],
            "wasmsign2": ["0.2.6"],
        },
        "1.239.0": {
            "wac": ["0.7.0", "0.8.0", "0.8.1"],
            "wit-bindgen": ["0.43.0", "0.46.0", "0.48.1", "0.49.0"],
            "wkg": ["0.11.0", "0.12.0", "0.13.0"],
            "wasmsign2": ["0.2.6"],
        },
    }

    if "wasm-tools" in tools_config:
        wasm_tools_version = tools_config["wasm-tools"]
        if wasm_tools_version in compatibility_matrix:
            compat_info = compatibility_matrix[wasm_tools_version]

            for tool, version in tools_config.items():
                if tool != "wasm-tools" and tool in compat_info:
                    if version not in compat_info[tool]:
                        warnings.append(
                            "Warning: {} version {} may not be compatible with wasm-tools {}. " +
                            "Recommended versions: {}".format(
                                tool,
                                version,
                                wasm_tools_version,
                                ", ".join(compat_info[tool]),
                            ),
                        )

    return warnings

def get_recommended_versions(stability = "stable"):
    """Get recommended tool versions for a given stability level

    Args:
        stability: Stability level ("stable" or "latest")

    Returns:
        Dict: Mapping of tool names to recommended versions
    """

    # Define default versions (sourced from tool_versions.bzl)
    default_versions = {
        "stable": {
            "wasm-tools": "1.239.0",
            "wac": "0.8.1",
            "wit-bindgen": "0.46.0",
            "wkg": "0.11.0",
            "wasmsign2": "0.2.6",
            "nodejs": "18.19.0",
            "jco": "1.4.0",
        },
        "latest": {
            "wasm-tools": "1.239.0",
            "wac": "0.8.1",
            "wit-bindgen": "0.46.0",
            "wkg": "0.11.0",
            "wasmsign2": "0.2.6",
            "nodejs": "18.19.0",
            "jco": "1.4.0",
        },
    }

    if stability not in default_versions:
        fail("Unknown stability level: {}. Available: {}".format(
            stability,
            ", ".join(default_versions.keys()),
        ))

    return default_versions[stability]
