"""SSH key generation using real ssh-keygen for OpenSSH format keys

This provides proper OpenSSH Ed25519 key generation using the ssh-keygen tool
from the openssh Bazel module, as opposed to wasmsign2 keygen which only
generates keys in its own format.
"""

load("//providers:providers.bzl", "WasmKeyInfo")

def _ssh_keygen_impl(ctx):
    """Implementation of ssh_keygen rule using real ssh-keygen"""

    # Declare output files
    private_key = ctx.actions.declare_file(ctx.attr.private_key_name)
    public_key = ctx.actions.declare_file(ctx.attr.public_key_name)

    # Build command arguments for ssh-keygen
    args = ctx.actions.args()
    args.add("-t", ctx.attr.key_type)  # Key type (ed25519, rsa, etc.)
    if ctx.attr.key_size:
        args.add("-b", str(ctx.attr.key_size))  # Key size (for RSA)
    args.add("-f", private_key.path)  # Output private key file
    args.add("-N", "")  # No passphrase
    args.add("-C", ctx.attr.comment)  # Comment

    # Run ssh-keygen to generate the key pair
    ctx.actions.run(
        executable = ctx.executable._ssh_keygen,
        arguments = [args],
        inputs = [],
        outputs = [private_key, public_key],
        mnemonic = "SshKeyGen",
        progress_message = "Generating SSH keys %s" % ctx.label,
        execution_requirements = {
            # ssh-keygen needs to run locally as it may need access to /dev/urandom
            "local": "1",
        },
    )

    # Create key info provider compatible with WASM signing
    key_info = WasmKeyInfo(
        public_key = public_key,
        secret_key = private_key,
        key_format = "openssh",  # These are actual OpenSSH format keys
        key_metadata = {
            "name": ctx.label.name,
            "algorithm": "Ed25519" if ctx.attr.key_type == "ed25519" else ctx.attr.key_type.upper(),
            "format": "openssh",
            "key_type": ctx.attr.key_type,
            "comment": ctx.attr.comment,
        },
    )

    return [
        key_info,
        DefaultInfo(files = depset([private_key, public_key])),
    ]

ssh_keygen = rule(
    implementation = _ssh_keygen_impl,
    attrs = {
        "private_key_name": attr.string(
            default = "id_ed25519",
            doc = "Name of the private key file to generate",
        ),
        "public_key_name": attr.string(
            default = "id_ed25519.pub",
            doc = "Name of the public key file to generate",
        ),
        "key_type": attr.string(
            default = "ed25519",
            doc = "SSH key type (ed25519, rsa, ecdsa, dsa)",
            values = ["ed25519", "rsa", "ecdsa", "dsa"],
        ),
        "key_size": attr.int(
            doc = "Key size in bits (for RSA keys, typically 2048 or 4096)",
        ),
        "comment": attr.string(
            default = "Generated by Bazel ssh_keygen rule",
            doc = "Comment to add to the key",
        ),
        "_ssh_keygen": attr.label(
            default = "@openssh//:ssh-keygen",
            executable = True,
            cfg = "exec",
            doc = "The ssh-keygen binary from openssh module",
        ),
    },
    doc = """
    Generates an SSH key pair using real ssh-keygen from OpenSSH.
    
    This rule produces actual OpenSSH format keys that can be used with
    wasmsign2's -Z flag for signing WebAssembly components.
    
    Example:
        ssh_keygen(
            name = "my_ssh_keys",
            key_type = "ed25519",
            comment = "WebAssembly component signing key",
        )
    """,
)