[package]
name = "checksum-validator-rust"
version = "0.1.0"
edition = "2021"
description = "Multi-language WebAssembly checksum validator - Rust component"
authors = ["WebAssembly Component Builder"]

[dependencies]
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
semver = "1.0"

# WebAssembly-specific configuration
[lib]
crate-type = ["cdylib"]

# Optimize for WebAssembly
[profile.release]
opt-level = "s"     # Optimize for size
lto = true          # Enable link-time optimization
codegen-units = 1   # Single codegen unit for better optimization
panic = "abort"     # Smaller binary size