name: Publish to BCR

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name to publish"
        required: true
        type: string

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  publish:
    name: Publish to Bazel Central Registry
    uses: bazel-contrib/publish-to-bcr/.github/workflows/publish.yaml@v6
    with:
      tag_name: ${{ inputs.tag_name || github.ref_name }}
      registry_fork: pulseengine/bazel-central-registry
      attest: true
    secrets:
      publish_token: ${{ secrets.BCR_PUBLISH_TOKEN }}
